# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Browse
    url: browse/
    weight: 20
    hasChildren: true
  - name: by author
    url: browse/author/
    parent: Browse
  - name: by incipit
    url: browse/incipit/
    parent: Browse
  - name: by source
    url: browse/source/
    parent: Browse
  - name: by title
    url: browse/title/
    parent: Browse
  - name: by century
    url: browse/century/
    parent: Browse
  - name: Concordances
    url: concordances/
    weight: 30
  - name: Search
    url: search/
    weight: 40
  - name: About
    url: about/
    weight: 50  
    
