# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Browse
    weight: 20
    hasChildren: true
  - name: by author
    url: author/
    parent: Browse
  - name: by contributor
    url: contributor/
    parent: Browse
  - name: by incipit
    url: incipit/
    parent: Browse
  - name: by source
    url: source/
    parent: Browse
  - name: by title
    url: title/
    parent: Browse
  - name: by century
    url: century/
  - name: Concordances
    url: concordances/
    weight: 30
  - name: Search
    url: search/
    weight: 40
