hugoblox:
  schema: "2.0"
  identity:
    name: "Thesaurus Musicarum Latinarum Revivificatus"
    type: person
    tagline: Latin music theory online
    description: An adaptation of a venerable database of Latin music-theoretical texts
  theme:
    mode: system
    pack: marine
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: serif
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: false
  footer:
    style: minimal
    language_switcher: false
  copyright:
    notice: "This work is licensed under {license}"
    license:
      type: cc              # cc | all_rights | custom
      allow_derivatives: true
      share_alike: false
      allow_commercial: true
  content:
    math:
      enable: false
    toc:
      enable: false
    reading_time:
      enable: false
  search:
    enable: false
