name = "Thesaurus Musicarum Latinarum Revivificatus"
license = "MIT"
licenselink = "https://github.com/HugoBlox/theme-landing-page/blob/main/LICENSE.md"
description = "An adaptation of a database of Latin music-theoretical texts."


tags = ["landing", "docs", "blog", "responsive", "minimal", "light", "dark", "multilingual", "dark mode", "tailwind", "company", "gallery"]
features = ["secure", "fast", "search", "dark mode", "widgets"]

# If the theme has a single author
[author]
  name = "Caleb Mutch"
  homepage = "https://calebmutch.com/"
